version: '3'

services:
  # api:
  #   build:
  #     context: .
  #   image: catalog-api
  #   container_name: catalog-api
  #   volumes:
  #     - .:/usr/src/app/
  #   ports:
  #     - 3333:3333
  #   command: yarn dev
  #   environment:
  #     NODE_ENV: ${NODE_ENV}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - backend
  postgres:
    image: postgres:12.2-alpine
    container_name: linx_postgres
    ports:
      - 5433:5432
    command: postgres -c idle_in_transaction_session_timeout='1min'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge
